INSERT INTO db.ExerciseType(name, categegory) VALUES ("Bar Dip", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Bench Press", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Cable Chest Press", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Close-Grip Bench Press", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Close-Grip Feet-Up Bench Press", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Decline Bench Press", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Chest Fly", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Chest Press", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Decline Chest Press", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Floor Press", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Pullover", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Feet-Up Bench Press", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Floor Press", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Incline Bench Press", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Incline Dumbbell Press", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Incline Push-Up", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Kneeling Incline Push-Up", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Kneeling Push-Up", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Machine Chest Fly", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Machine Chest Press", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Pec Deck", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Push-Up", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Push-Up Against Wall", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Push-Ups With Feet in Rings", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Resistance Band Chest Fly", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Smith Machine Bench Press", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Smith Machine Incline Bench Press", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Standing Cable Chest Fly", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Standing Resistance Band Chest Fly", SELECT Id FROM db.Category WHERE name IN "chest");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Band External Shoulder Rotation", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Band Internal Shoulder Rotation", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Band Pull-Apart", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Barbell Front Raise", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Barbell Rear Delt Row", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Barbell Upright Row", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Behind the Neck Press", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Cable Lateral Raise", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Cable Rear Delt Row", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Front Raise", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Horizontal Internal Shoulder Rotation", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Horizontal External Shoulder Rotation", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Lateral Raise", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Rear Delt Row", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Shoulder Press", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Face Pull", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Front Hold", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Lying Dumbbell External Shoulder Rotation", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Lying Dumbbell Internal Shoulder Rotation", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Machine Lateral Raise", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Machine Shoulder Press", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Monkey Row", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Overhead Press", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Plate Front Raise", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Power Jerk", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Push Press", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Reverse Dumbbell Flyes", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Reverse Machine Fly", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Seated Dumbbell Shoulder Press", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Seated Barbell Overhead Press", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Seated Smith Machine Shoulder Press", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Snatch Grip Behind the Neck Press", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Squat Jerk", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Split Jerk", SELECT Id FROM db.Category WHERE name IN "shoulder");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Barbell Curl", SELECT Id FROM db.Category WHERE name IN "bicep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Barbell Preacher Curl", SELECT Id FROM db.Category WHERE name IN "bicep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Bodyweight Curl", SELECT Id FROM db.Category WHERE name IN "bicep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Cable Curl With Bar", SELECT Id FROM db.Category WHERE name IN "bicep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Cable Curl With Rope", SELECT Id FROM db.Category WHERE name IN "bicep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Concentration Curl", SELECT Id FROM db.Category WHERE name IN "bicep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Curl", SELECT Id FROM db.Category WHERE name IN "bicep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Preacher Curl", SELECT Id FROM db.Category WHERE name IN "bicep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Hammer Curl", SELECT Id FROM db.Category WHERE name IN "bicep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Incline Dumbbell Curl", SELECT Id FROM db.Category WHERE name IN "bicep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Machine Bicep Curl", SELECT Id FROM db.Category WHERE name IN "bicep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Spider Curl", SELECT Id FROM db.Category WHERE name IN "bicep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Barbell Standing Triceps Extension", SELECT Id FROM db.Category WHERE name IN "tricep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Barbell Lying Triceps Extension", SELECT Id FROM db.Category WHERE name IN "tricep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Bench Dip", SELECT Id FROM db.Category WHERE name IN "tricep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Close-Grip Push-Up", SELECT Id FROM db.Category WHERE name IN "tricep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Lying Triceps Extension", SELECT Id FROM db.Category WHERE name IN "tricep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Standing Triceps Extension", SELECT Id FROM db.Category WHERE name IN "tricep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Overhead Cable Triceps Extension", SELECT Id FROM db.Category WHERE name IN "tricep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Tricep Bodyweight Extension", SELECT Id FROM db.Category WHERE name IN "tricep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Tricep Pushdown With Bar", SELECT Id FROM db.Category WHERE name IN "tricep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Tricep Pushdown With Rope", SELECT Id FROM db.Category WHERE name IN "tricep");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Air Squat", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Barbell Hack Squat", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Barbell Lunge", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Barbell Walking Lunge", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Belt Squat", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Body Weight Lunge", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Box Squat", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Bulgarian Split Squat", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Chair Squat", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Lunge", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Squat", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Front Squat", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Goblet Squat", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Hack Squat Machine", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Half Air Squat", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Hip Adduction Machine", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Landmine Hack Squat", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Landmine Squat", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Leg Extension", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Leg Press", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Lying Leg Curl", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Pause Squat", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Romanian Deadlift", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Safety Bar Squat", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Seated Leg Curl", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Shallow Body Weight Lunge", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Side Lunges (Bodyweight)", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Smith Machine Squat", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Squat", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Step Up", SELECT Id FROM db.Category WHERE name IN "leg");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Back Extension", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Barbell Row", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Barbell Shrug", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Block Snatch", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Cable Close Grip Seated Row", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Cable Wide Grip Seated Row", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Chin-Up", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Clean", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Clean and Jerk", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Deadlift", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Deficit Deadlift", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Deadlift", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Row", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Shrug", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Floor Back Extension", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Good Morning", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Hang Clean", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Hang Power Clean", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Hang Power Snatch", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Hang Snatch", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Inverted Row", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Inverted Row with Underhand Grip", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Kettlebell Swing", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Lat Pulldown With Pronated Grip", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Lat Pulldown With Supinated Grip", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("One-Handed Cable Row", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("One-Handed Lat Pulldown", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Pause Deadlift", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Pendlay Row", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Power Clean", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Power Snatch", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Pull-Up", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Rack Pull", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Seal Row", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Seated Machine Row", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Snatch", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Snatch Grip Deadlift", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Stiff-Legged Deadlift", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Straight Arm Lat Pulldown", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Sumo Deadlift", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("T-Bar Row", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Trap Bar Deadlift With High Handles", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Trap Bar Deadlift With Low Handles", SELECT Id FROM db.Category WHERE name IN "back");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Banded Side Kicks", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Cable Pull Through", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Clamshells", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Romanian Deadlift", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Frog Pumps", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Fire Hydrants", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Frog Pumps", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Glute Bridge", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Hip Abduction Against Band", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Hip Abduction Machine", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Hip Thrust", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Hip Thrust Machine", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Hip Thrust With Band Around Knees", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Lateral Walk With Band", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Machine Glute Kickbacks", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("One-Legged Glute Bridge", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("One-Legged Hip Thrust", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Romanian Deadlift", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Single Leg Romanian Deadlift", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Standing Glute Kickback in Machine", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Step Up", SELECT Id FROM db.Category WHERE name IN "glute");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Cable Crunch", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Crunch", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dead Bug", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Hanging Leg Raise", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Hanging Knee Raise", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Hanging Sit-Up", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("High to Low Wood Chop with Band", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Horizontal Wood Chop with Band", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Kneeling Ab Wheel Roll-Out", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Kneeling Plank", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Kneeling Side Plank", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Lying Leg Raise", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Lying Windshield Wiper", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Lying Windshield Wiper with Bent Knees", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Machine Crunch", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Mountain Climbers", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Oblique Crunch", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Oblique Sit-Up", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Plank", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Side Plank", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Sit-Up", SELECT Id FROM db.Category WHERE name IN "ab");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Eccentric Heel Drop", SELECT Id FROM db.Category WHERE name IN "calves");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Heel Raise", SELECT Id FROM db.Category WHERE name IN "calves");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Seated Calf Raise", SELECT Id FROM db.Category WHERE name IN "calves");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Standing Calf Raise", SELECT Id FROM db.Category WHERE name IN "calves");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Barbell Wrist Curl", SELECT Id FROM db.Category WHERE name IN "forearm/grip");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Barbell Wrist Curl Behind the Back", SELECT Id FROM db.Category WHERE name IN "forearm/grip");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Bar Hang", SELECT Id FROM db.Category WHERE name IN "forearm/grip");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Dumbbell Wrist Curl", SELECT Id FROM db.Category WHERE name IN "forearm/grip");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Farmers Walk", SELECT Id FROM db.Category WHERE name IN "forearm/grip");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Fat Bar Deadlift", SELECT Id FROM db.Category WHERE name IN "forearm/grip");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Gripper", SELECT Id FROM db.Category WHERE name IN "forearm/grip");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("One-Handed Bar Hang", SELECT Id FROM db.Category WHERE name IN "forearm/grip");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Plate Pinch", SELECT Id FROM db.Category WHERE name IN "forearm/grip");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Plate Wrist Curl", SELECT Id FROM db.Category WHERE name IN "forearm/grip");
INSERT INTO db.ExerciseType(name, categegory) VALUES ("Towel Pull-Up", SELECT Id FROM db.Category WHERE name IN "forearm/grip");