FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD=password

COPY ./SqlData/Tables/ /docker-entrypoint-initdb.d/ 


# FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
 
# WORKDIR /src
# COPY workoutapicore.csproj .

# RUN dotnet restore "workoutapicore.csproj"
# COPY . .
# RUN dotnet publish "workoutapicore.csproj" -c Release -o /publish

# # WORKDIR /publish
# # ENV ASPNETCORE_URLS=http://+:80/
# # EXPOSE 80
# #HEALTHCHECK CMD curl --fail http://localhost || exit 1
# CMD ["./workoutapicore"]
# FROM mcr.microsoft.com/dotnet/aspnet:7.0 as final
# WORKDIR /app
# COPY --from=build /publish .
# ENTRYPOINT ["dotnet", "OrderProcessingWorker.dll"]

