CREATE DATABASE IF NOT EXISTS db;
USE db;
--INSERTS into db.Categegory
INSERT INTO db.Category(Id, Name) VALUES (1, 'chest');
INSERT INTO db.Category(Id, Name) VALUES (2, 'shoulder');
INSERT INTO db.Category(Id, Name) VALUES (3, 'bicep');
INSERT INTO db.Category(Id, Name) VALUES (4, 'tricep');
INSERT INTO db.Category(Id, Name) VALUES (5, 'leg');
INSERT INTO db.Category(Id, Name) VALUES (6, 'back');
INSERT INTO db.Category(Id, Name) VALUES (7, 'glute');
INSERT INTO db.Category(Id, Name) VALUES (8, 'ab');
INSERT INTO db.Category(Id, Name) VALUES (9, 'calves');
INSERT INTO db.Category(Id, Name) VALUES (10, 'forearm/grip');

--INSERTS into db.EerciseType
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Bar Dip', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Bench Press', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Cable Chest Press', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Close-Grip Bench Press', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Close-Grip Feet-Up Bench Press', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Decline Bench Press', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Chest Fly', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Chest Press', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Decline Chest Press', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Floor Press', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Pullover', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Feet-Up Bench Press', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Floor Press', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Incline Bench Press', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Incline Dumbbell Press', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Incline Push-Up', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Kneeling Incline Push-Up', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Kneeling Push-Up', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Machine Chest Fly', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Machine Chest Press', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Pec Deck', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Push-Up', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Push-Up Against Wall', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Push-Ups With Feet in Rings', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Resistance Band Chest Fly', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Smith Machine Bench Press', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Smith Machine Incline Bench Press', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Standing Cable Chest Fly', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Standing Resistance Band Chest Fly', 1);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Band External Shoulder Rotation', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Band Internal Shoulder Rotation', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Band Pull-Apart', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Barbell Front Raise', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Barbell Rear Delt Row', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Barbell Upright Row', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Behind the Neck Press', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Cable Lateral Raise', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Cable Rear Delt Row', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Front Raise', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Horizontal Internal Shoulder Rotation', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Horizontal External Shoulder Rotation', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Lateral Raise', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Rear Delt Row', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Shoulder Press', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Face Pull', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Front Hold', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Lying Dumbbell External Shoulder Rotation', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Lying Dumbbell Internal Shoulder Rotation', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Machine Lateral Raise', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Machine Shoulder Press', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Monkey Row', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Overhead Press', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Plate Front Raise', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Power Jerk', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Push Press', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Reverse Dumbbell Flyes', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Reverse Machine Fly', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Seated Dumbbell Shoulder Press', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Seated Barbell Overhead Press', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Seated Smith Machine Shoulder Press', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Snatch Grip Behind the Neck Press', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Squat Jerk', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Split Jerk', 2);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Barbell Curl', 3);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Barbell Preacher Curl', 3);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Bodyweight Curl', 3);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Cable Curl With Bar', 3);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Cable Curl With Rope', 3);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Concentration Curl', 3);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Curl', 3);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Preacher Curl', 3);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Hammer Curl', 3);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Incline Dumbbell Curl', 3);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Machine Bicep Curl', 3);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Spider Curl', 3);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Barbell Standing Triceps Extension', 4);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Barbell Lying Triceps Extension', 4);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Bench Dip', 4);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Close-Grip Push-Up', 4);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Lying Triceps Extension', 4);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Standing Triceps Extension', 4);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Overhead Cable Triceps Extension', 4);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Tricep Bodyweight Extension', 4);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Tricep Pushdown With Bar', 4);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Tricep Pushdown With Rope', 4);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Air Squat', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Barbell Hack Squat', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Barbell Lunge', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Barbell Walking Lunge', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Belt Squat', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Body Weight Lunge', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Box Squat', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Bulgarian Split Squat', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Chair Squat', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Lunge', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Squat', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Front Squat', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Goblet Squat', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Hack Squat Machine', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Half Air Squat', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Hip Adduction Machine', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Landmine Hack Squat', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Landmine Squat', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Leg Extension', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Leg Press', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Lying Leg Curl', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Pause Squat', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Romanian Deadlift', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Safety Bar Squat', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Seated Leg Curl', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Shallow Body Weight Lunge', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Side Lunges (Bodyweight)', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Smith Machine Squat', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Squat', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Step Up', 5);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Back Extension', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Barbell Row', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Barbell Shrug', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Block Snatch', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Cable Close Grip Seated Row', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Cable Wide Grip Seated Row', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Chin-Up', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Clean', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Clean and Jerk', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Deadlift', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Deficit Deadlift', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Deadlift', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Row', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Shrug', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Floor Back Extension', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Good Morning', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Hang Clean', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Hang Power Clean', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Hang Power Snatch', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Hang Snatch', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Inverted Row', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Inverted Row with Underhand Grip', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Kettlebell Swing', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Lat Pulldown With Pronated Grip', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Lat Pulldown With Supinated Grip', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('One-Handed Cable Row', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('One-Handed Lat Pulldown', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Pause Deadlift', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Pendlay Row', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Power Clean', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Power Snatch', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Pull-Up', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Rack Pull', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Seal Row', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Seated Machine Row', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Snatch', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Snatch Grip Deadlift', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Stiff-Legged Deadlift', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Straight Arm Lat Pulldown', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Sumo Deadlift', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('T-Bar Row', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Trap Bar Deadlift With High Handles', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Trap Bar Deadlift With Low Handles', 6);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Banded Side Kicks', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Cable Pull Through', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Clamshells', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Romanian Deadlift', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Frog Pumps', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Fire Hydrants', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Frog Pumps', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Glute Bridge', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Hip Abduction Against Band', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Hip Abduction Machine', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Hip Thrust', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Hip Thrust Machine', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Hip Thrust With Band Around Knees', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Lateral Walk With Band', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Machine Glute Kickbacks', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('One-Legged Glute Bridge', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('One-Legged Hip Thrust', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Romanian Deadlift', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Single Leg Romanian Deadlift', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Standing Glute Kickback in Machine', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Step Up', 7);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Cable Crunch', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Crunch', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dead Bug', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Hanging Leg Raise', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Hanging Knee Raise', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Hanging Sit-Up', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('High to Low Wood Chop with Band', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Horizontal Wood Chop with Band', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Kneeling Ab Wheel Roll-Out', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Kneeling Plank', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Kneeling Side Plank', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Lying Leg Raise', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Lying Windshield Wiper', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Lying Windshield Wiper with Bent Knees', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Machine Crunch', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Mountain Climbers', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Oblique Crunch', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Oblique Sit-Up', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Plank', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Side Plank', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Sit-Up', 8);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Eccentric Heel Drop', 9);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Heel Raise', 9);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Seated Calf Raise', 9);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Standing Calf Raise', 9);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Barbell Wrist Curl', 10);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Barbell Wrist Curl Behind the Back', 10);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Bar Hang', 10);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Dumbbell Wrist Curl', 10);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Farmers Walk', 10);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Fat Bar Deadlift', 10);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Gripper', 10);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('One-Handed Bar Hang', 10);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Plate Pinch', 10);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Plate Wrist Curl', 10);
INSERT INTO db.ExerciseType(Name, CategoryId) VALUES ('Towel Pull-Up', 10);
